.\" $Id$
.TH "WL2KSERIAL" "1" "November 2010" "wl2kserial 0.5 " "User Commands"
.SH "NAME"
wl2kserial \- manual page for wl2kserial 0.5
.SH "SYNOPSIS"
.B wl2kserial
\fI\-c target\-call \-d device \-b baudrate options\fR
.SH "DESCRIPTION"
.TP
\fB\-c\fR  \fB\-\-target\-call\fR
Set callsign to call
.TP
\fB\-d\fR  \fB\-\-device\fR
Set serial device name
.TP
\fB\-b\fR  \fB\-\-baudrate\fR
Set baud rate of serial device
.TP
\fB\-m\fR  \fB\-\-modem\fR
Set modem type, either P4dragon or PTC-IIPro (default)
.TP
\fB\-t\fR  \fB\-\-timeout\fR
Set timeout in seconds
.TP
\fB\-e\fR  \fB\-\-email\-address\fR
Set your e\-mail address
.TP
\fB\-s\fR  \fB\-\-send\-only\fR
Send a message without receiving any
.TP
\fB\-P\fR  \fB\-\-wl2k-passwd\fR
Set password for Winlink secure login
.TP
\fB\-v\fR  \fB\-\-version\fR
Display version of this program
.TP
\fB\-V\fR  \fB\-\-verbose\fR
Print verbose messages
.TP
\fB\-C\fR  \fB\-\-configuration\fR
Display configuration only
.TP
\fB\-h\fR  \fB\-\-help\fR
Display this usage info
.SH "AUTHORS"
.LP
Nicholas S. Castellano N2QZ <n2qz@arrl.net>
.SH "SEE ALSO"
wl2kax25(1), wl2ktelnet(1), ax25(4), wl2k.conf(5)

Winlink 2000 is an all\-volunteer, non\-profit project of the Amateur Radio Safety Foundation, Inc.
