.\" $Id$
.TH "WL2KTELNET" "1" "November 2010" "wl2ktelnet 0.5 " "User Commands"
.SH "NAME"
wl2ktelnet \- manual page for wl2ktelnet 0.5
.SH "SYNOPSIS"
.B wl2ktelnet
[\fIoptions\fR] [\fIHOSTNAME PORT\fR]
.SH "DESCRIPTION"
.TP 
\fB\-c\fR  \fB\-\-target\-call\fR
Set callsign to call
.TP 
\fB\-p\fR  \fB\-\-password\fR
Set password for login
.TP 
\fB\-t\fR  \fB\-\-timeout\fR
Set timeout in seconds
.TP
\fB\-e\fR  \fB\-\-email\-address\fR
Set your e\-mail address
.TP 
\fB\-s\fR  \fB\-\-send\-only\fR
Send a message without receiving any
.TP 
\fB\-v\fR  \fB\-\-version\fR
Display program version only
.TP 
\fB\-V\fR  \fB\-\-verbose\fR
Print verbose messages
.TP
\fB\-C\fR  \fB\-\-configuration\fR
Display configuration only
.TP 
\fB\-h\fR  \fB\-\-help\fR
Display this usage info
.SH "AUTHORS"
.LP 
Nicholas S. Castellano N2QZ <n2qz@arrl.net>
.SH "SEE ALSO"
wl2kax25(1), wl2kserial(1), ax25(4), wl2k.conf(5)

Winlink 2000 is an all\-volunteer, non\-profit project of the Amateur Radio Safety Foundation, Inc.
