.TH "wl2kax25" "1" "1.6" "Nicholas Castellano, et. al" "paclink-unix"
.SH "NAME"
.LP 
wl2kax25 \- Linux Winlink2000 AX.25 Interface
.SH "SYNTAX"
.LP 
wl2kax25 \fImycall\fR \fIyourcall\fR \fIax25port\fR \fItimeoutsecs\fR \fIemailaddress\fR
.SH "DESCRIPTION"
.LP 
wl2kax25 invokes the packlink\-unix AX.25 interface.  It is used to transfer data between the local paclink\-unix client and a Winlink 2000 gateway RMS.

wl2kax25 establishes an AX.25 connection between the client node using the call \fImycall\fR and the RMS gateway \fIyourcall\fR.  The connection is made over the port specified by \fIax25port\fR.  wl2kax25 will wait for \fItimeoutsecs\fR seconds in order to establish the link before giving up.  All Winlink 2000 traffic that is received from the RMS is forwarded to the local emal address, \fIemailaddress\fR.

Additionally, wl2kax25 will attempt to upload any outbound messages that have been queued by packlink\-unix to the RMS.
.SH "CAVEAT"
.LP 
.TP 
This man page will change soon.
.SH "OPTIONS"
.LP 
.TP 
None
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
wl2kax25 w1aw kb1aev\-10 sm0 30 me@myhost
.SH "AUTHORS"
.LP 
Nicholas S. Castellano N2QZ <n2qz@arrl.net>
.SH "SEE ALSO"
mail.wl2k(1), mime2wl(1), wl2ktelnet(1), wl2kserial(1), wl2kmime(1), ax25(4)

Winlink 2000 is an all\-volunteer, non\-profit project of the Amateur Radio Safety Foundation, Inc.
