#! /bin/sh

cleanup () {
	rm -f binmail ascmail1.test binmail.test binmail1.test
}

set -e
set -x

trap 'exit 77' 0

uudecode ${srcdir}/binmail.uue

trap 'cleanup ; exit 1' 0

./lzhuf_1 e ${srcdir}/ascmail binmail.test
cmp binmail binmail.test
./lzhuf_1 e1 ${srcdir}/ascmail binmail1.test
./lzhuf_1 d1 binmail1.test ascmail1.test
cmp ${srcdir}/ascmail ascmail1.test
./lzhuf_1 e1 ${srcdir}/ascmail binmail1.test 2>&1 | grep f708 || exit 1
./lzhuf_1 e1 ${srcdir}/ascmail binmail1.test 2>&1 | grep 20216 || exit 1
./lzhuf_1 d1 binmail1.test ascmail1.test 2>&1 | grep f708 || exit 1
./lzhuf_1 d1 binmail1.test ascmail1.test 2>&1 | grep 20216 || exit 1

trap '' 0

cleanup
exit 0
