#! /bin/sh

cleanup () {
	rm -f binmail ascmail1.test binmail.test binmail1.test
}

set -e
set -x

trap 'exit 77' 0

uudecode binmail.uue

trap 'cleanup ; exit 1' 0

./lzhuf_1 e2 ascmail binmail.test
cmp binmail binmail.test
./lzhuf_1 e1 ascmail binmail1.test
./lzhuf_1 d1 binmail1.test ascmail1.test
cmp ascmail ascmail1.test
./lzhuf_1 e1 ascmail binmail1.test | grep f708 || exit 1
./lzhuf_1 e1 ascmail binmail1.test | grep 20216 || exit 1
./lzhuf_1 d1 binmail1.test ascmail1.test | grep f708 || exit 1
./lzhuf_1 d1 binmail1.test ascmail1.test | grep 20216 || exit 1

trap '' 0

cleanup
exit 0
